/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrystalRouteImport } from './routes/crystal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIndexRouteImport } from './routes/p.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiSvgGenRouteImport } from './routes/api/svg-gen'
import { Route as ApiSvgGenSlugRouteImport } from './routes/api/svg-gen.$slug'
import { Route as ApiPosterPreviewSlugRouteImport } from './routes/api/poster-preview.$slug'

const CrystalRoute = CrystalRouteImport.update({
  id: '/crystal',
  path: '/crystal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIndexRoute = PIndexRouteImport.update({
  id: '/p/',
  path: '/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSvgGenRoute = ApiSvgGenRouteImport.update({
  id: '/api/svg-gen',
  path: '/api/svg-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSvgGenSlugRoute = ApiSvgGenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiSvgGenRoute,
} as any)
const ApiPosterPreviewSlugRoute = ApiPosterPreviewSlugRouteImport.update({
  id: '/api/poster-preview/$slug',
  path: '/api/poster-preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crystal': typeof CrystalRoute
  '/api/svg-gen': typeof ApiSvgGenRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/p/': typeof PIndexRoute
  '/api/poster-preview/$slug': typeof ApiPosterPreviewSlugRoute
  '/api/svg-gen/$slug': typeof ApiSvgGenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crystal': typeof CrystalRoute
  '/api/svg-gen': typeof ApiSvgGenRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/p': typeof PIndexRoute
  '/api/poster-preview/$slug': typeof ApiPosterPreviewSlugRoute
  '/api/svg-gen/$slug': typeof ApiSvgGenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crystal': typeof CrystalRoute
  '/api/svg-gen': typeof ApiSvgGenRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/p/': typeof PIndexRoute
  '/api/poster-preview/$slug': typeof ApiPosterPreviewSlugRoute
  '/api/svg-gen/$slug': typeof ApiSvgGenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crystal'
    | '/api/svg-gen'
    | '/p/$slug'
    | '/p/'
    | '/api/poster-preview/$slug'
    | '/api/svg-gen/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crystal'
    | '/api/svg-gen'
    | '/p/$slug'
    | '/p'
    | '/api/poster-preview/$slug'
    | '/api/svg-gen/$slug'
  id:
    | '__root__'
    | '/'
    | '/crystal'
    | '/api/svg-gen'
    | '/p/$slug'
    | '/p/'
    | '/api/poster-preview/$slug'
    | '/api/svg-gen/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrystalRoute: typeof CrystalRoute
  ApiSvgGenRoute: typeof ApiSvgGenRouteWithChildren
  PSlugRoute: typeof PSlugRoute
  PIndexRoute: typeof PIndexRoute
  ApiPosterPreviewSlugRoute: typeof ApiPosterPreviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crystal': {
      id: '/crystal'
      path: '/crystal'
      fullPath: '/crystal'
      preLoaderRoute: typeof CrystalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/': {
      id: '/p/'
      path: '/p'
      fullPath: '/p/'
      preLoaderRoute: typeof PIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/svg-gen': {
      id: '/api/svg-gen'
      path: '/api/svg-gen'
      fullPath: '/api/svg-gen'
      preLoaderRoute: typeof ApiSvgGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/svg-gen/$slug': {
      id: '/api/svg-gen/$slug'
      path: '/$slug'
      fullPath: '/api/svg-gen/$slug'
      preLoaderRoute: typeof ApiSvgGenSlugRouteImport
      parentRoute: typeof ApiSvgGenRoute
    }
    '/api/poster-preview/$slug': {
      id: '/api/poster-preview/$slug'
      path: '/api/poster-preview/$slug'
      fullPath: '/api/poster-preview/$slug'
      preLoaderRoute: typeof ApiPosterPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSvgGenRouteChildren {
  ApiSvgGenSlugRoute: typeof ApiSvgGenSlugRoute
}

const ApiSvgGenRouteChildren: ApiSvgGenRouteChildren = {
  ApiSvgGenSlugRoute: ApiSvgGenSlugRoute,
}

const ApiSvgGenRouteWithChildren = ApiSvgGenRoute._addFileChildren(
  ApiSvgGenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrystalRoute: CrystalRoute,
  ApiSvgGenRoute: ApiSvgGenRouteWithChildren,
  PSlugRoute: PSlugRoute,
  PIndexRoute: PIndexRoute,
  ApiPosterPreviewSlugRoute: ApiPosterPreviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
